version: '3'
services:
    nginx:
        image: nginx
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d:cached
        expose:
            - 80
        environment:
            TZ: Asia/Shanghai
        restart: on-failure
        networks:
            mirrors:
                aliases:
                   - mirrors.jenkins-ci.org

    jenkins:
        image: jenkins/jenkins:lts
        ports:
            - "2080:8080"
            - "50000:50000"
        environment:
            TZ: Asia/Shanghai
        restart: on-failure
        volumes:
            - ./jenkins_home:/var/jenkins_home:cached
        networks:
            - mirrors
        depends_on:
            - nginx
networks:
    mirrors: