FROM jenkins/jenkins:latest

ADD ./jenkins_image/sources.list /etc/apt/sources.list

USER root
RUN apt-get -y update && apt-get install -y build-essential libssl-dev libffi-dev python3-dev python3-pip

USER jenkins

